In [13]:
import numpy as np

In [14]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [15]:
%time for _ in range(10) : my_arr2 = my_arr * 2

CPU times: total: 0 ns
Wall time: 27 ms


In [16]:
%time for _ in range(10) : my_list2 = [x * 2 for x in  my_list]

CPU times: total: 891 ms
Wall time: 1.07 s


In [17]:
import numpy as np

In [18]:
data = np.random.randn(2,3) # Creating matrices with 2 rows and 3 columns

In [19]:
data

array([[ 0.39455629, -1.79835931,  1.04101169],
       [ 0.30850347, -0.63138722,  0.95109127]])

In [20]:
data * 10

array([[  3.94556289, -17.98359308,  10.41011694],
       [  3.08503467,  -6.31387216,   9.51091273]])

In [21]:
data + data 

array([[ 0.78911258, -3.59671862,  2.08202339],
       [ 0.61700693, -1.26277443,  1.90218255]])

In [22]:
data.shape

(2, 3)

In [23]:
data.dtype

dtype('float64')

In [24]:
data = [6,7.5,8,0,1]
arr1 = np.array(data)

In [25]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [26]:
#Creating ndarrays


In [27]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [28]:
arr2 = np.array(data2)

In [29]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
arr2.ndim

2

In [31]:
arr2.shape

(2, 4)

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [40]:
np.empty((2,3,2))

array([[[9.85226473e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.11260619e-306, 4.12072893e-033]],

       [[9.17769260e-072, 6.89494244e-042],
        [2.80416383e-032, 3.98644478e-062],
        [4.35457901e-061, 2.32212244e-056]]])

In [41]:
arr1 = np.array([1,2,3], dtype = np.float64) #ndarray of floats

In [43]:
arr2 = np.array([1,2,3], dtype = np.int32) #ndarray of integers

In [44]:
arr1.dtype

dtype('float64')

In [45]:
arr2.dtype

dtype('int32')

In [51]:
arr = np.array([1,2,3,4,5])

In [48]:
#Arithmetic with NumPyArrays

In [54]:
arr = np.array([[1,2,3],[4,5,6]])

In [55]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [57]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [61]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [62]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [63]:
arr2d= np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [64]:
arr2d[0][2]

3

In [65]:
arr2d[0,2]

3

In [73]:
arr3d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr3d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [74]:
arr3d[0]

array([1, 2, 3])

In [75]:
arr3d[1,0]

4

In [77]:
#Boolean Indexing

In [79]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4)

In [80]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [81]:
data

array([[ 0.22404943, -0.06681135, -1.4606937 , -1.41884204],
       [-1.22390993,  0.05465326,  1.00445604, -0.62876911],
       [-0.06302765, -0.83186117,  0.59221079,  0.93042934],
       [-1.81556432, -1.89409189, -0.21891467,  0.57632698],
       [ 0.59406747,  0.52766391, -1.75974119,  0.12554583],
       [-1.96417274,  0.74847205,  0.61721768,  2.19654279],
       [ 0.21323505,  0.60091528, -0.94379838, -1.06031207]])

In [82]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [83]:
data[names=='Bob']

array([[ 0.22404943, -0.06681135, -1.4606937 , -1.41884204],
       [-1.81556432, -1.89409189, -0.21891467,  0.57632698]])

In [78]:
#Transposing Arrays and Swapping Axes

In [85]:
array=np.arange(15).reshape((3,5))

In [86]:
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [88]:
array.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [89]:
arrays = np.random.randn(6,3)

In [90]:
arrays

array([[-0.82927891, -0.34731674,  0.01274479],
       [ 0.14938893,  0.25967905,  1.33921156],
       [ 0.85711626,  0.69461992,  0.23349038],
       [ 0.87562848,  0.26009805,  1.3680007 ],
       [ 0.67791743, -0.85740339,  0.81737435],
       [-1.07897008, -0.37336034,  1.97745674]])

In [94]:
np.dot(arrays.T,arrays)

array([[ 3.83514255e+00,  9.71530849e-01,  7.97883096e-03],
       [ 9.71530849e-01,  1.61274847e+00, -5.77783367e-01],
       [ 7.97883096e-03, -5.77783367e-01,  8.29802971e+00]])

In [95]:
#Universal Functions: Fast Element-Wise Array Functions 


In [96]:
arr = np.random.randn(7) * 5
arr

array([ 0.98604034, -0.19122891,  3.90426421,  3.30995725, -0.1669996 ,
        5.85496292,  2.46473349])

In [100]:
remainder, whole_part = np.modf(arr)

In [101]:
remainder

array([ 0.98604034, -0.19122891,  0.90426421,  0.30995725, -0.1669996 ,
        0.85496292,  0.46473349])

In [102]:
whole_part

array([ 0., -0.,  3.,  3., -0.,  5.,  2.])

In [104]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = [True,False,True,True,False]

In [105]:
result = np.where(cond,xarr,yarr)

In [106]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [107]:
arr.mean()

2.3088185288487564

In [109]:
np.mean(arr)

2.3088185288487564

In [110]:
arr.sum()

16.161729701941294

In [113]:
arr = np.random.randn(5,4)

In [114]:
arr

array([[-0.42889786,  0.87385405,  1.31057041, -0.70328955],
       [-1.53517527,  0.63419146,  1.37180545, -0.09988945],
       [ 1.07875454, -0.07516605, -0.07298386,  0.63546363],
       [ 0.40942933,  0.44469568, -1.44616032,  0.82451703],
       [-0.76674069, -0.17188365, -1.36526944,  1.04877458]])

In [115]:
arr.mean(axis=1)

array([ 0.26305926,  0.09273305,  0.39151706,  0.05812043, -0.3137798 ])

In [116]:
kuki = np.arange(10)

In [117]:
np.save('brojevi',kuki)

In [119]:
np.load('brojevi.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])